name: Generate and Zip Images

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Essential to see existing files for naming logic

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install System Requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools<58.0.0"
        pip install seleniumbase selenium-stealth

    - name: Execute Script
      run: |
        mkdir -p images
        xvfb-run python main.py

    - name: Commit and Push Zip
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add images/*.zip
        git commit -m "Add new compressed image batch" || echo "No changes to commit"
        git push
