name: Generate Raw and NoBG Zips

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install System Requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb libgl1

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools<58.0.0"
        pip install seleniumbase selenium-stealth opencv-python-headless numpy

    - name: Execute Script
      run: |
        mkdir -p images
        mkdir -p remove
        xvfb-run python main.py

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git pull origin main # Ensure we have latest batch numbers
        git add images/*.zip
        git add remove/*.zip
        git commit -m "New batch: gen_${{ github.run_number }}" || echo "No changes"
        git push origin main
